### PR TITLE
feat: Add supports notarize file

### PR DESCRIPTION
**Pull request by panther7**
#153

### CODE REVIEW

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
I don't believe that you can staple the app _inside_ a zip file, or at least that was the limitation when notarization was first released.  Is that limitation no longer a problem?

**Comment by panther7** [comment]
I don't know if app in zip is supported.
In our project we using dmg file, which is supported.

I can modify this PR for dmg/pkg only.

@MarshallOfSound

**Comment by panther7** [comment]
From docs:

> notarytool submit works only with UDIF disk images, signed "flat" installer packages, and zip files. notarytool will do a shallow validation of the file before submission. Passing any other file format in file-path to notarytool submit will result in an error.

I think, that is not problem, if someone try submit "unsupported" file, apple backend return error.

**Comment by MarshallOfSound** [comment]
Superseded by https://github.com/electron/notarize/pull/169

**Pull request closed without merging**
